export enum ComponentType {
    AnimatedSprite,
    AudioListener,
    AudioSource,
    Behaviour,
    BoxCollider,
    Camera,
    CapsuleCollider,
    CircleCollider,
    Collider,
    Component,
    ParticleSystem,
    PolygonRenderer,
    PolygonCollider,
    RigidBody,
    Texture,
    TileMap,
    Transform
}